# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    twig.extension.country:
        class: ALT\AppBundle\Twig\CountryExtension
        tags:
            - { name: twig.extension }

    twig.extension.image:
        class: ALT\AppBundle\Twig\ImageExtension
        tags:
            - { name: twig.extension }

    app.manager.commande:
        class: ALT\AppBundle\Manager\CommandeManager
        arguments: ["@doctrine.orm.entity_manager", "%stripe_api%"]

    app.manager.mail:
         class: ALT\AppBundle\Manager\MailManager
         arguments: ["@templating.engine.twig", "%mailer_user%", "@swiftmailer.mailer"]