alt_app_accueil:
    path:     /
    defaults:
        _controller: ALTAppBundle:Front:accueil

alt_app_infos:
    path:     /infos
    defaults:
        _controller: ALTAppBundle:Front:infos

alt_app_pannier:
    path:     /pannier
    defaults:
        _controller: ALTAppBundle:Front:pannier

alt_app_coordonnees:
    path:     /coordonnees
    defaults:
        _controller: ALTAppBundle:Front:coordonnees

alt_app_paiement:
    path:     /paiement
    defaults:
        _controller: ALTAppBundle:Front:paiement

alt_app_confirmation:
    path:     /confirmation
    defaults:
        _controller: ALTAppBundle:Front:confirmation

alt_app_aide:
    path:     /aide
    defaults:
        _controller: ALTAppBundle:Front:aide

alt_app_cgv:
    path:     /cgv
    defaults:
        _controller: ALTAppBundle:Front:cgv

alt_app_tarifs:
    path:     /tarifs
    defaults:
        _controller: ALTAppBundle:Front:tarifs